//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 06-Dec-2012 by the VDM++ to JAVA Code Generator
// (v8.0 - Mon 09-Jul-2007 09:32:40)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class ActorObjectTest extends Test {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=ActorObjectTestSentinel KEEP=NO
  class ActorObjectTestSentinel extends TestSentinel {

    public final int actorTest = 1;

    public final int objectTest = 2;

    public final int corruptedMessage = 3;

    public final int lostInCommunication = 4;

    public final int actorObjectCommunicating = 5;

    public final int actorSpeakingWithoutMessage = 6;

    public final int crazyActorThatspeaksToHimself = 7;

    public final int actorObjectCommunicatingAndSomeoneAlone = 8;

    public final int nr_functions = 9;


    public ActorObjectTestSentinel () throws CGException {}


    public ActorObjectTestSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=ActorObjectTestSentinel
;

// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new ActorObjectTestSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=ActorObjectTest KEEP=NO
  public ActorObjectTest () throws CGException {}
// ***** VDMTOOLS END Name=ActorObjectTest


// ***** VDMTOOLS START Name=objectTest KEEP=NO
  public void objectTest () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).objectTest);
    try {

      Diagram d = new Diagram();
      vdm_Object o = new vdm_Object(new String("anObject"));
      vdm_Object o2 = new vdm_Object(new String("anObject2"), new String("this is an object"));
      Message m = new Message(new Integer(1));
      d.addObjects((vdm_Object) o);
      d.addObjects((vdm_Object) o2);
      d.addMessages((Message) m);
      d.sendMessage((Lifeline) o, (Lifeline) o2, (Message) m);
      Boolean tmpArg_v_16 = null;
      Boolean var1_17 = null;
      Boolean var1_18 = null;
      Boolean var1_19 = null;
      Boolean var1_20 = null;
      Boolean var1_21 = null;
      String var1_22 = null;
      var1_22 = o.name;
      var1_21 = new Boolean(UTIL.equals(var1_22, new String("anObject")));
      {
        if ((var1_20 = var1_21).booleanValue()) {

          Boolean var2_25 = null;
          String var1_26 = null;
          var1_26 = o2.name;
          var2_25 = new Boolean(UTIL.equals(var1_26, new String("anObject2")));
          var1_20 = var2_25;
        }
      }
      {
        if ((var1_19 = var1_20).booleanValue()) {

          Boolean var2_29 = null;
          Integer var1_30 = null;
          var1_30 = m.identifier;
          var2_29 = new Boolean(var1_30.intValue() == new Integer(1).intValue());
          var1_19 = var2_29;
        }
      }
      {
        if ((var1_18 = var1_19).booleanValue()) {

          Boolean var2_33 = null;
          HashSet var2_35 = new HashSet();
          var2_35 = d.objects;
          var2_33 = new Boolean(var2_35.contains(o));
          var1_18 = var2_33;
        }
      }
      {
        if ((var1_17 = var1_18).booleanValue()) {

          Boolean var2_37 = null;
          HashSet var2_39 = new HashSet();
          var2_39 = d.objects;
          var2_37 = new Boolean(var2_39.contains(o2));
          var1_17 = var2_37;
        }
      }
      {
        if ((tmpArg_v_16 = var1_17).booleanValue()) {

          Boolean var2_41 = null;
          HashSet var2_43 = new HashSet();
          var2_43 = d.messages;
          var2_41 = new Boolean(var2_43.contains(m));
          tmpArg_v_16 = var2_41;
        }
      }
      Assert(tmpArg_v_16);
      d.remObjects((vdm_Object) o);
      d.remObjects((vdm_Object) o2);
      Boolean tmpArg_v_50 = null;
      Boolean var1_51 = null;
      HashSet var2_53 = new HashSet();
      var2_53 = d.objects;
      var1_51 = new Boolean(!var2_53.contains(o));
      {
        if ((tmpArg_v_50 = var1_51).booleanValue()) {

          Boolean var2_55 = null;
          HashSet var2_57 = new HashSet();
          var2_57 = d.objects;
          var2_55 = new Boolean(!var2_57.contains(o2));
          tmpArg_v_50 = var2_55;
        }
      }
      Assert(tmpArg_v_50);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).objectTest);
    }
  }
// ***** VDMTOOLS END Name=objectTest


// ***** VDMTOOLS START Name=actorTest KEEP=NO
  public void actorTest () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).actorTest);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      Actor a2 = new Actor(new String("anActor2"));
      Message m = new Message(new Integer(1));
      d.addActors((Actor) a);
      d.addActors((Actor) a2);
      d.addMessages((Message) m);
      d.sendMessage((Lifeline) a, (Lifeline) a2, (Message) m);
      Boolean tmpArg_v_15 = null;
      Boolean var1_16 = null;
      Boolean var1_17 = null;
      Boolean var1_18 = null;
      Boolean var1_19 = null;
      Boolean var1_20 = null;
      String var1_21 = null;
      var1_21 = a.name;
      var1_20 = new Boolean(UTIL.equals(var1_21, new String("anActor")));
      {
        if ((var1_19 = var1_20).booleanValue()) {

          Boolean var2_24 = null;
          String var1_25 = null;
          var1_25 = a2.name;
          var2_24 = new Boolean(UTIL.equals(var1_25, new String("anActor2")));
          var1_19 = var2_24;
        }
      }
      {
        if ((var1_18 = var1_19).booleanValue()) {

          Boolean var2_28 = null;
          Integer var1_29 = null;
          var1_29 = m.identifier;
          var2_28 = new Boolean(var1_29.intValue() == new Integer(1).intValue());
          var1_18 = var2_28;
        }
      }
      {
        if ((var1_17 = var1_18).booleanValue()) {

          Boolean var2_32 = null;
          HashSet var2_34 = new HashSet();
          var2_34 = d.actors;
          var2_32 = new Boolean(var2_34.contains(a));
          var1_17 = var2_32;
        }
      }
      {
        if ((var1_16 = var1_17).booleanValue()) {

          Boolean var2_36 = null;
          HashSet var2_38 = new HashSet();
          var2_38 = d.actors;
          var2_36 = new Boolean(var2_38.contains(a2));
          var1_16 = var2_36;
        }
      }
      {
        if ((tmpArg_v_15 = var1_16).booleanValue()) {

          Boolean var2_40 = null;
          HashSet var2_42 = new HashSet();
          var2_42 = d.messages;
          var2_40 = new Boolean(var2_42.contains(m));
          tmpArg_v_15 = var2_40;
        }
      }
      Assert(tmpArg_v_15);
      d.remActors((Actor) a);
      d.remActors((Actor) a2);
      Boolean tmpArg_v_49 = null;
      Boolean var1_50 = null;
      HashSet var2_52 = new HashSet();
      var2_52 = d.actors;
      var1_50 = new Boolean(!var2_52.contains(a));
      {
        if ((tmpArg_v_49 = var1_50).booleanValue()) {

          Boolean var2_54 = null;
          HashSet var2_56 = new HashSet();
          var2_56 = d.actors;
          var2_54 = new Boolean(!var2_56.contains(a2));
          tmpArg_v_49 = var2_54;
        }
      }
      Assert(tmpArg_v_49);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).actorTest);
    }
  }
// ***** VDMTOOLS END Name=actorTest


// ***** VDMTOOLS START Name=actorObjectCommunicating KEEP=NO
  public void actorObjectCommunicating () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).actorObjectCommunicating);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      vdm_Object o = new vdm_Object(new String("anObject"), new String("this is an object"));
      Message m = new Message(new Integer(1));
      d.addActors((Actor) a);
      d.addObjects((vdm_Object) o);
      d.addMessages((Message) m);
      d.sendMessage((Lifeline) o, (Lifeline) a, (Message) m);
      Boolean tmpArg_v_16 = null;
      Boolean var1_17 = null;
      Boolean var1_18 = null;
      Boolean var1_19 = null;
      Boolean var1_20 = null;
      Boolean var1_21 = null;
      String var1_22 = null;
      var1_22 = a.name;
      var1_21 = new Boolean(UTIL.equals(var1_22, new String("anActor")));
      {
        if ((var1_20 = var1_21).booleanValue()) {

          Boolean var2_25 = null;
          String var1_26 = null;
          var1_26 = o.name;
          var2_25 = new Boolean(UTIL.equals(var1_26, new String("anObject")));
          var1_20 = var2_25;
        }
      }
      {
        if ((var1_19 = var1_20).booleanValue()) {

          Boolean var2_29 = null;
          Integer var1_30 = null;
          var1_30 = m.identifier;
          var2_29 = new Boolean(var1_30.intValue() == new Integer(1).intValue());
          var1_19 = var2_29;
        }
      }
      {
        if ((var1_18 = var1_19).booleanValue()) {

          Boolean var2_33 = null;
          HashSet var2_35 = new HashSet();
          var2_35 = d.actors;
          var2_33 = new Boolean(var2_35.contains(a));
          var1_18 = var2_33;
        }
      }
      {
        if ((var1_17 = var1_18).booleanValue()) {

          Boolean var2_37 = null;
          HashSet var2_39 = new HashSet();
          var2_39 = d.objects;
          var2_37 = new Boolean(var2_39.contains(o));
          var1_17 = var2_37;
        }
      }
      {
        if ((tmpArg_v_16 = var1_17).booleanValue()) {

          Boolean var2_41 = null;
          HashSet var2_43 = new HashSet();
          var2_43 = d.messages;
          var2_41 = new Boolean(var2_43.contains(m));
          tmpArg_v_16 = var2_41;
        }
      }
      Assert(tmpArg_v_16);
      d.remMessages((Message) m);
      Boolean tmpArg_v_48 = null;
      Boolean var1_49 = null;
      Boolean var1_50 = null;
      HashSet var2_52 = new HashSet();
      var2_52 = d.actors;
      var1_50 = new Boolean(var2_52.contains(a));
      {
        if ((var1_49 = var1_50).booleanValue()) {

          Boolean var2_54 = null;
          HashSet var2_56 = new HashSet();
          var2_56 = d.objects;
          var2_54 = new Boolean(var2_56.contains(o));
          var1_49 = var2_54;
        }
      }
      {
        if ((tmpArg_v_48 = var1_49).booleanValue()) {

          Boolean var2_58 = null;
          HashSet var2_60 = new HashSet();
          var2_60 = d.messages;
          var2_58 = new Boolean(!var2_60.contains(m));
          tmpArg_v_48 = var2_58;
        }
      }
      Assert(tmpArg_v_48);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).actorObjectCommunicating);
    }
  }
// ***** VDMTOOLS END Name=actorObjectCommunicating


// ***** VDMTOOLS START Name=actorObjectCommunicatingAndSomeoneAlone KEEP=NO
  public void actorObjectCommunicatingAndSomeoneAlone () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).actorObjectCommunicatingAndSomeoneAlone);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      vdm_Object o = new vdm_Object(new String("anObject"));
      Actor someoneAlone = new Actor(new String("someoneAlone"));
      Message m = new Message(new Integer(1), new String("this is a message and I hope you get it"));
      Gate g = new Gate(new Integer(3), m, new Integer(1));
      d.addActors((Actor) a);
      d.addObjects((vdm_Object) o);
      d.addMessages((Message) m);
      d.addGates((Gate) g);
      d.addGateToLifeline((Lifeline) o, (Gate) g);
      d.sendMessage((Lifeline) a, (Lifeline) o, (Message) m);
      Boolean tmpArg_v_25 = null;
      Boolean var1_26 = null;
      Boolean var1_27 = null;
      Boolean var1_28 = null;
      String var1_29 = null;
      var1_29 = a.name;
      var1_28 = new Boolean(UTIL.equals(var1_29, new String("anActor")));
      {
        if ((var1_27 = var1_28).booleanValue()) {

          Boolean var2_32 = null;
          String var1_33 = null;
          var1_33 = o.name;
          var2_32 = new Boolean(UTIL.equals(var1_33, new String("anObject")));
          var1_27 = var2_32;
        }
      }
      {
        if ((var1_26 = var1_27).booleanValue()) {

          Boolean var2_36 = null;
          Integer var1_37 = null;
          var1_37 = m.identifier;
          var2_36 = new Boolean(var1_37.intValue() == new Integer(1).intValue());
          var1_26 = var2_36;
        }
      }
      {
        if ((tmpArg_v_25 = var1_26).booleanValue()) {

          Boolean var2_40 = null;
          String var1_41 = null;
          var1_41 = someoneAlone.name;
          var2_40 = new Boolean(UTIL.equals(var1_41, new String("someoneAlone")));
          tmpArg_v_25 = var2_40;
        }
      }
      Assert(tmpArg_v_25);
      d.remMessages((Message) m);
      Boolean tmpArg_v_47 = null;
      Boolean var1_48 = null;
      Boolean var1_49 = null;
      Boolean var1_50 = null;
      Boolean var1_51 = null;
      HashSet var2_53 = new HashSet();
      var2_53 = d.actors;
      var1_51 = new Boolean(var2_53.contains(a));
      {
        if ((var1_50 = var1_51).booleanValue()) {

          Boolean var2_55 = null;
          HashSet var2_57 = new HashSet();
          var2_57 = d.objects;
          var2_55 = new Boolean(var2_57.contains(o));
          var1_50 = var2_55;
        }
      }
      {
        if ((var1_49 = var1_50).booleanValue()) {

          Boolean var2_59 = null;
          HashSet var2_61 = new HashSet();
          var2_61 = d.messages;
          var2_59 = new Boolean(!var2_61.contains(m));
          var1_49 = var2_59;
        }
      }
      {
        if ((var1_48 = var1_49).booleanValue()) {

          Boolean var2_63 = null;
          HashSet var2_65 = new HashSet();
          var2_65 = d.gates;
          var2_63 = new Boolean(var2_65.contains(g));
          var1_48 = var2_63;
        }
      }
      {
        if ((tmpArg_v_47 = var1_48).booleanValue()) {

          Boolean var2_67 = null;
          HashSet var2_69 = new HashSet();
          Vector unArg_70 = null;
          unArg_70 = o.gates;
          HashSet set_72 = new HashSet();
          Enumeration enm_73 = unArg_70.elements();
          while ( enm_73.hasMoreElements())
            set_72.add(enm_73.nextElement());
          var2_69 = set_72;
          var2_67 = new Boolean(var2_69.contains(g));
          tmpArg_v_47 = var2_67;
        }
      }
      Assert(tmpArg_v_47);
      d.remGates((Gate) g);
      Boolean tmpArg_v_77 = null;
      Boolean var1_78 = null;
      Boolean var1_79 = null;
      HashSet var2_81 = new HashSet();
      var2_81 = d.objects;
      var1_79 = new Boolean(var2_81.contains(o));
      {
        if ((var1_78 = var1_79).booleanValue()) {

          Boolean var2_83 = null;
          HashSet var2_85 = new HashSet();
          var2_85 = d.gates;
          var2_83 = new Boolean(!var2_85.contains(g));
          var1_78 = var2_83;
        }
      }
      {
        if ((tmpArg_v_77 = var1_78).booleanValue()) {

          Boolean var2_87 = null;
          HashSet var2_89 = new HashSet();
          Vector unArg_90 = null;
          unArg_90 = o.gates;
          HashSet set_92 = new HashSet();
          Enumeration enm_93 = unArg_90.elements();
          while ( enm_93.hasMoreElements())
            set_92.add(enm_93.nextElement());
          var2_89 = set_92;
          var2_87 = new Boolean(!var2_89.contains(g));
          tmpArg_v_77 = var2_87;
        }
      }
      Assert(tmpArg_v_77);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).actorObjectCommunicatingAndSomeoneAlone);
    }
  }
// ***** VDMTOOLS END Name=actorObjectCommunicatingAndSomeoneAlone


// ***** VDMTOOLS START Name=crazyActorThatspeaksToHimself KEEP=NO
  public void crazyActorThatspeaksToHimself () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).crazyActorThatspeaksToHimself);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      Message m = new Message(new Integer(1));
      Gate g = new Gate(new Integer(3), m, new Integer(1));
      d.addActors((Actor) a);
      d.addMessages((Message) m);
      d.addGates((Gate) g);
      d.addGateToLifeline((Lifeline) a, (Gate) g);
      d.sendMessageToSelf((Lifeline) a, (Message) m);
      Boolean tmpArg_v_19 = null;
      Boolean var1_20 = null;
      String var1_21 = null;
      var1_21 = a.name;
      var1_20 = new Boolean(UTIL.equals(var1_21, new String("anActor")));
      {
        if ((tmpArg_v_19 = var1_20).booleanValue()) {

          Boolean var2_24 = null;
          Integer var1_25 = null;
          var1_25 = m.identifier;
          var2_24 = new Boolean(var1_25.intValue() == new Integer(1).intValue());
          tmpArg_v_19 = var2_24;
        }
      }
      Assert(tmpArg_v_19);
      d.remMessages((Message) m);
      Boolean tmpArg_v_31 = null;
      Boolean var1_32 = null;
      Boolean var1_33 = null;
      Boolean var1_34 = null;
      HashSet var2_36 = new HashSet();
      var2_36 = d.actors;
      var1_34 = new Boolean(var2_36.contains(a));
      {
        if ((var1_33 = var1_34).booleanValue()) {

          Boolean var2_38 = null;
          HashSet var2_40 = new HashSet();
          var2_40 = d.messages;
          var2_38 = new Boolean(!var2_40.contains(m));
          var1_33 = var2_38;
        }
      }
      {
        if ((var1_32 = var1_33).booleanValue()) {

          Boolean var2_42 = null;
          Message var1_43 = null;
          var1_43 = g.msgToSend;
          var2_42 = new Boolean(!UTIL.equals(var1_43, m));
          var1_32 = var2_42;
        }
      }
      {
        if ((tmpArg_v_31 = var1_32).booleanValue()) {

          Boolean var2_46 = null;
          Message var1_47 = null;
          var1_47 = g.msgToReceive;
          var2_46 = new Boolean(!UTIL.equals(var1_47, m));
          tmpArg_v_31 = var2_46;
        }
      }
      Assert(tmpArg_v_31);
      Boolean tmpArg_v_51 = null;
      Boolean var1_52 = null;
      Boolean var1_53 = null;
      HashSet var2_55 = new HashSet();
      var2_55 = d.actors;
      var1_53 = new Boolean(var2_55.contains(a));
      {
        if ((var1_52 = var1_53).booleanValue()) {

          Boolean var2_57 = null;
          HashSet var2_59 = new HashSet();
          var2_59 = d.gates;
          var2_57 = new Boolean(var2_59.contains(g));
          var1_52 = var2_57;
        }
      }
      {
        if ((tmpArg_v_51 = var1_52).booleanValue()) {

          Boolean var2_61 = null;
          HashSet var2_63 = new HashSet();
          Vector unArg_64 = null;
          unArg_64 = a.gates;
          HashSet set_66 = new HashSet();
          Enumeration enm_67 = unArg_64.elements();
          while ( enm_67.hasMoreElements())
            set_66.add(enm_67.nextElement());
          var2_63 = set_66;
          var2_61 = new Boolean(var2_63.contains(g));
          tmpArg_v_51 = var2_61;
        }
      }
      Assert(tmpArg_v_51);
      d.remGates((Gate) g);
      Boolean tmpArg_v_71 = null;
      Boolean var1_72 = null;
      Boolean var1_73 = null;
      HashSet var2_75 = new HashSet();
      var2_75 = d.actors;
      var1_73 = new Boolean(var2_75.contains(a));
      {
        if ((var1_72 = var1_73).booleanValue()) {

          Boolean var2_77 = null;
          HashSet var2_79 = new HashSet();
          var2_79 = d.gates;
          var2_77 = new Boolean(!var2_79.contains(g));
          var1_72 = var2_77;
        }
      }
      {
        if ((tmpArg_v_71 = var1_72).booleanValue()) {

          Boolean var2_81 = null;
          HashSet var2_83 = new HashSet();
          Vector unArg_84 = null;
          unArg_84 = a.gates;
          HashSet set_86 = new HashSet();
          Enumeration enm_87 = unArg_84.elements();
          while ( enm_87.hasMoreElements())
            set_86.add(enm_87.nextElement());
          var2_83 = set_86;
          var2_81 = new Boolean(!var2_83.contains(g));
          tmpArg_v_71 = var2_81;
        }
      }
      Assert(tmpArg_v_71);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).crazyActorThatspeaksToHimself);
    }
  }
// ***** VDMTOOLS END Name=crazyActorThatspeaksToHimself


// ***** VDMTOOLS START Name=actorSpeakingWithoutMessage KEEP=NO
  public void actorSpeakingWithoutMessage () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).actorSpeakingWithoutMessage);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      Message m = new Message(new Integer(1));
      d.sendMessageToSelf((Lifeline) a, (Message) m);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).actorSpeakingWithoutMessage);
    }
  }
// ***** VDMTOOLS END Name=actorSpeakingWithoutMessage


// ***** VDMTOOLS START Name=lostInCommunication KEEP=NO
  public void lostInCommunication () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).lostInCommunication);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      Message m = new Message(new Integer(1));
      Gate g = new Gate(new Integer(3), m, new Integer(1));
      d.addActors((Actor) a);
      d.remGates((Gate) g);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).lostInCommunication);
    }
  }
// ***** VDMTOOLS END Name=lostInCommunication


// ***** VDMTOOLS START Name=corruptedMessage KEEP=NO
  public void corruptedMessage () throws CGException {

    sentinel.entering(((ActorObjectTestSentinel) sentinel).corruptedMessage);
    try {

      Diagram d = new Diagram();
      Actor a = new Actor(new String("anActor"));
      Message m = new Message(new Integer(1));
      d.addActors((Actor) a);
      d.remMessages((Message) m);
    }
    finally {
      sentinel.leaving(((ActorObjectTestSentinel) sentinel).corruptedMessage);
    }
  }
// ***** VDMTOOLS END Name=corruptedMessage

}
;
