//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 06-Dec-2012 by the VDM++ to JAVA Code Generator
// (v8.0 - Mon 09-Jul-2007 09:32:40)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class Gate implements EvaluatePP {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=identifier KEEP=NO
  public volatile Integer identifier = null;
// ***** VDMTOOLS END Name=identifier

// ***** VDMTOOLS START Name=msgToSend KEEP=NO
  public volatile Message msgToSend = null;
// ***** VDMTOOLS END Name=msgToSend

// ***** VDMTOOLS START Name=msgToReceive KEEP=NO
  public volatile Message msgToReceive = null;
// ***** VDMTOOLS END Name=msgToReceive

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=GateSentinel KEEP=NO
  class GateSentinel extends Sentinel {

    public final int remMsgToSend = 0;

    public final int remMsgToReceive = 1;

    public final int Gate_u_u3_uN_un_uMessage_uN = 2;

    public final int Gate_u_u3_uN_un_uMessage_un_uMessage = 3;

    public final int nr_functions = 4;


    public GateSentinel () throws CGException {}


    public GateSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=GateSentinel
;

// ***** VDMTOOLS START Name=evaluatePP KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return new Boolean(true);
  }
// ***** VDMTOOLS END Name=evaluatePP


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new GateSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=Gate KEEP=NO
  public Gate () throws CGException {
    try {

      setSentinel();
      msgToSend = (Message) new Message(new Integer(9999));
      msgToReceive = (Message) new Message(new Integer(9999));
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Gate


// ***** VDMTOOLS START Name=Gate KEEP=NO
  public Gate (final Integer newIdentifier, final Message newMsg, final Integer dir) throws CGException {

    try {

      setSentinel();
      msgToSend = (Message) new Message(new Integer(9999));
      msgToReceive = (Message) new Message(new Integer(9999));
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      identifier = UTIL.NumberToInt(UTIL.clone(newIdentifier));
      if (new Boolean(dir.intValue() == new Integer(0).intValue()).booleanValue()) 
        msgToSend = (Message) UTIL.clone(newMsg);
      else 
        msgToReceive = (Message) UTIL.clone(newMsg);
    }
  }
// ***** VDMTOOLS END Name=Gate


// ***** VDMTOOLS START Name=pre_Gate KEEP=NO
  public Boolean pre_Gate (final Integer newIdentifier, final Message newMsg, final Integer dir) throws CGException {

    Boolean varRes_4 = null;
    {
      if (!(varRes_4 = new Boolean(dir.intValue() == new Integer(1).intValue())).booleanValue()) 
        varRes_4 = new Boolean(dir.intValue() == new Integer(0).intValue());
    }
    return varRes_4;
  }
// ***** VDMTOOLS END Name=pre_Gate


// ***** VDMTOOLS START Name=Gate KEEP=NO
  public Gate (final Integer newIdentifier, final Message newMsgToSend, final Message newMsgToReceive) throws CGException {

    try {

      setSentinel();
      msgToSend = (Message) new Message(new Integer(9999));
      msgToReceive = (Message) new Message(new Integer(9999));
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      identifier = UTIL.NumberToInt(UTIL.clone(newIdentifier));
      msgToSend = (Message) UTIL.clone(newMsgToSend);
      msgToReceive = (Message) UTIL.clone(newMsgToReceive);
    }
  }
// ***** VDMTOOLS END Name=Gate


// ***** VDMTOOLS START Name=remMsgToSend KEEP=NO
  public void remMsgToSend (final Message oldMessage) throws CGException {

    sentinel.entering(((GateSentinel) sentinel).remMsgToSend);
    try {

      Message rhs_2 = null;
      Integer arg_3 = null;
      arg_3 = oldMessage.identifier;
      rhs_2 = new Message(arg_3);
      msgToSend = (Message) UTIL.clone(rhs_2);
    }
    finally {
      sentinel.leaving(((GateSentinel) sentinel).remMsgToSend);
    }
  }
// ***** VDMTOOLS END Name=remMsgToSend


// ***** VDMTOOLS START Name=pre_remMsgToSend KEEP=NO
  public Boolean pre_remMsgToSend (final Message oldMessage) throws CGException {
    return new Boolean(UTIL.equals(msgToSend, oldMessage));
  }
// ***** VDMTOOLS END Name=pre_remMsgToSend


// ***** VDMTOOLS START Name=remMsgToReceive KEEP=NO
  public void remMsgToReceive (final Message oldMessage) throws CGException {

    sentinel.entering(((GateSentinel) sentinel).remMsgToReceive);
    try {

      Message rhs_2 = null;
      Integer arg_3 = null;
      arg_3 = oldMessage.identifier;
      rhs_2 = new Message(arg_3);
      msgToReceive = (Message) UTIL.clone(rhs_2);
    }
    finally {
      sentinel.leaving(((GateSentinel) sentinel).remMsgToReceive);
    }
  }
// ***** VDMTOOLS END Name=remMsgToReceive


// ***** VDMTOOLS START Name=pre_remMsgToReceive KEEP=NO
  public Boolean pre_remMsgToReceive (final Message oldMessage) throws CGException {
    return new Boolean(UTIL.equals(msgToReceive, oldMessage));
  }
// ***** VDMTOOLS END Name=pre_remMsgToReceive

}
;
