//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 06-Dec-2012 by the VDM++ to JAVA Code Generator
// (v8.0 - Mon 09-Jul-2007 09:32:40)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class Fragment implements EvaluatePP {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=name KEEP=NO
  public volatile String name = null;
// ***** VDMTOOLS END Name=name

// ***** VDMTOOLS START Name=characteristic KEEP=NO
  public volatile String characteristic = null;
// ***** VDMTOOLS END Name=characteristic

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=FragmentSentinel KEEP=NO
  class FragmentSentinel extends Sentinel {

    public final int Fragment = 0;

    public final int nr_functions = 1;


    public FragmentSentinel () throws CGException {}


    public FragmentSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=FragmentSentinel
;

// ***** VDMTOOLS START Name=evaluatePP KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return new Boolean(true);
  }
// ***** VDMTOOLS END Name=evaluatePP


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new FragmentSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=Fragment KEEP=NO
  public Fragment () throws CGException {
    try {
      setSentinel();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Fragment


// ***** VDMTOOLS START Name=Fragment KEEP=NO
  public Fragment (final String newName, final String newCharacteristic) throws CGException {

    try {
      setSentinel();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      name = UTIL.ConvertToString(UTIL.clone(newName));
      characteristic = UTIL.ConvertToString(UTIL.clone(newCharacteristic));
    }
  }
// ***** VDMTOOLS END Name=Fragment


// ***** VDMTOOLS START Name=pre_Fragment KEEP=NO
  public Boolean pre_Fragment (final String newName, final String newCharacteristic) throws CGException {

    Boolean varRes_3 = null;
    {
      if ((varRes_3 = new Boolean((new Integer(newName.length()).intValue()) > (new Integer(0).intValue()))).booleanValue()) 
        varRes_3 = new Boolean((new Integer(newCharacteristic.length()).intValue()) > (new Integer(0).intValue()));
    }
    return varRes_3;
  }
// ***** VDMTOOLS END Name=pre_Fragment

}
;
