//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 06-Dec-2012 by the VDM++ to JAVA Code Generator
// (v8.0 - Mon 09-Jul-2007 09:32:40)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class vdm_Object extends Lifeline {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=description KEEP=NO
  public volatile String description = null;
// ***** VDMTOOLS END Name=description


// ***** VDMTOOLS START Name=ObjectSentinel KEEP=NO
  class ObjectSentinel extends LifelineSentinel {

    public final int Object_u_u1_us_uC = 5;

    public final int Object_u_u2_us_uC_us_uC = 6;

    public final int nr_functions = 7;


    public ObjectSentinel () throws CGException {}


    public ObjectSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=ObjectSentinel
;

// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new ObjectSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_Object KEEP=NO
  public vdm_Object () throws CGException {}
// ***** VDMTOOLS END Name=vdm_Object


// ***** VDMTOOLS START Name=vdm_Object KEEP=NO
  public vdm_Object (final String newName) throws CGException {
    super(newName);
  }
// ***** VDMTOOLS END Name=vdm_Object


// ***** VDMTOOLS START Name=vdm_Object KEEP=NO
  public vdm_Object (final String newName, final String newDescription) throws CGException {

    description = UTIL.ConvertToString(UTIL.clone(newDescription));
    super(newName);
  }
// ***** VDMTOOLS END Name=vdm_Object


// ***** VDMTOOLS START Name=pre_Object KEEP=NO
  public Boolean pre_Object (final String newName, final String newDescription) throws CGException {
    return new Boolean((new Integer(newDescription.length()).intValue()) > (new Integer(0).intValue()));
  }
// ***** VDMTOOLS END Name=pre_Object

}
;
